# Generated by Django 4.2.20 on 2025-06-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pmo', '__first__'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=60)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('project_role', models.CharField(max_length=60)),
                ('allocated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('booked_hours', models.DurationField(blank=True, null=True)),
                ('new_description', models.CharField(blank=True, max_length=100, null=True)),
                ('worked_hours', models.DurationField()),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=10)),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.employee')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmo.project')),
                ('task_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.projecttasks')),
            ],
        ),
    ]
