# Generated by Django 5.1.2 on 2025-05-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetimesheet',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
