# Generated by Django 5.1.2 on 2025-10-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeetimesheet_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimesheet',
            name='skillset',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
