# Generated by Django 5.1.2 on 2025-10-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeetimesheet_skillset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetimesheet',
            name='skillset',
        ),
    ]
