# Generated by Django 5.1.2 on 2025-12-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
