# Generated by Django 4.2.20 on 2025-06-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='change_password_required',
            field=models.BooleanField(default=True),
        ),
    ]
