# Generated by Django 4.2.20 on 2025-06-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userprofile_change_password_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='change_password_required',
        ),
    ]
