# Generated by Django 4.2.20 on 2025-06-03 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('band_grade', models.CharField(max_length=4)),
                ('joining_date', models.DateField()),
                ('manager', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_role', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('task_code', models.AutoField(primary_key=True, serialize=False)),
                ('project_type', models.CharField(max_length=30)),
                ('task_group', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('billable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
            ],
        ),
    ]
