# Generated by Django 4.2.20 on 2025-06-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='relieving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
