# Generated by Django 4.2.20 on 2025-06-04 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_employee_relieving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectroles',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='projectroles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
