# Generated by Django 4.2.20 on 2025-06-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_projectroles_created_at_projectroles_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttasks',
            name='billable',
        ),
    ]
