# Generated by Django 5.1.2 on 2025-09-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_remove_projecttasks_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
