# Generated by Django 5.1.2 on 2025-09-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_employee_email_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
