# Generated by Django 5.1.2 on 2025-09-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_alter_employee_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=30)),
                ('geo_region', models.CharField(max_length=10)),
                ('location_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=30)),
                ('geo_region', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='relieving_date',
        ),
        migrations.RemoveField(
            model_name='projectroles',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectroles',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projecttasks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projecttasks',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='billable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
    ]
