# Generated by Django 5.1.2 on 2025-09-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_assetcategories_assetmodel_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetCategories',
            new_name='AssetCategory',
        ),
    ]
