# Generated by Django 5.1.2 on 2025-09-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_rename_assetcategories_assetcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetCategory',
        ),
        migrations.DeleteModel(
            name='AssetModel',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
