# Generated by Django 5.1.2 on 2025-09-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_delete_assetcategory_delete_assetmodel_delete_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='supplier',
        ),
    ]
