# Generated by Django 5.1.2 on 2025-09-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_rename_supplier_name_supplier_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='geo_region',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='geo_region',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
