# Generated by Django 5.1.2 on 2025-09-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_assetcategories_assetmodel_status'),
        ('master_data', '0013_alter_company_address_alter_company_company_and_more'),
    ]

    operations = [
    ]
