# Generated by Django 5.1.2 on 2025-09-30 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_merge_20250930_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttasks',
            name='billable',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='relieving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectroles',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='projectroles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
