# Generated by Django 5.1.2 on 2025-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_remove_projecttasks_billable_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='geo_region',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location_name',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='geo_region',
            field=models.CharField(blank=True),
        ),
    ]
