# Generated by Django 5.1.2 on 2025-10-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_alter_company_country_alter_company_geo_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skillset',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
