# Generated by Django 5.1.2 on 2025-10-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_alter_company_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='geo_region',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='geo_region',
            field=models.CharField(blank=True),
        ),
    ]
