# Generated by Django 5.1.2 on 2025-10-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_employee_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skillset',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
