# Generated by Django 5.1.2 on 2025-12-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_alter_company_country_alter_company_geo_region_and_more'),
        ('master_data', '0017_alter_company_country_alter_company_geo_region_and_more'),
    ]

    operations = [
    ]
