# Generated by Django 5.1.2 on 2025-10-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_alter_employee_skillset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='skillset',
            new_name='skill',
        ),
    ]
