# Generated by Django 5.1.2 on 2025-10-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_rename_skillset_employee_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skill',
        ),
    ]
