# Generated by Django 5.1.2 on 2025-10-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_remove_employee_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
