# Generated by Django 5.1.2 on 2025-10-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_employee_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skill',
        ),
        migrations.AddField(
            model_name='employee',
            name='primary_skill',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='secondary_skill',
            field=models.JSONField(default=list),
        ),
    ]
