# Generated by Django 5.1.2 on 2025-10-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_remove_employee_skill_employee_primary_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contractor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='project_specific_hire',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
