# Generated by Django 5.1.2 on 2025-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_employee_contractor_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
