# Generated by Django 5.1.2 on 2025-10-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0024_employee_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skill',
        ),
    ]
