# Generated by Django 5.1.2 on 2025-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_remove_employee_skill'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('email__isnull', True), _negated=True), models.Q(('email', ''), _negated=True)), fields=('email',), name='unique_non_empty_email'),
        ),
    ]
