# Generated by Django 5.1.2 on 2025-12-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_merge_20251212_1620'),
        ('master_data', '0026_employee_unique_non_empty_email'),
    ]

    operations = [
    ]
