# Generated by Django 5.1.2 on 2025-10-08 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0016_alter_company_country_alter_company_geo_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=10)),
                ('asset_category', models.CharField(max_length=40)),
                ('asset_sub_category', models.CharField(max_length=40)),
                ('asset_name', models.CharField(max_length=40)),
                ('asset_tag', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=40)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=80, null=True)),
                ('location', models.CharField(max_length=60)),
                ('image', models.FileField(blank=True, null=True, upload_to='hardware/images/')),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('byod', models.BooleanField(default=False)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_copy', models.FileField(blank=True, null=True, upload_to='hardware/invoices/')),
                ('admin_user_name', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=255)),
                ('assignment_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('assignment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('assignment_from_date', models.DateField(blank=True, null=True)),
                ('assignment_to_date', models.DateField(blank=True, null=True)),
                ('assignment_details', models.JSONField(blank=True, default=list)),
                ('last_changed_by', models.CharField(max_length=50)),
                ('last_changed_datetime', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_assignments', to='master_data.assetmodel')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.supplier')),
            ],
        ),
    ]
