# Generated by Django 5.1.2 on 2025-10-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwareassignment',
            name='assignment_details',
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('changed_by', models.CharField(max_length=50)),
                ('changed_datetime', models.DateTimeField(auto_now_add=True)),
                ('hardware_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='inventory.hardwareassignment')),
            ],
            options={
                'verbose_name': 'Assignment History',
                'verbose_name_plural': 'Assignment Histories',
                'ordering': ['-from_date', '-changed_datetime'],
            },
        ),
    ]
