# Generated by Django 5.1.2 on 2025-10-16 11:34

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_hardwareassignment_assignment_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenthistory',
            name='from_date',
            field=models.DateField(default=inventory.models.default_from_date),
        ),
        migrations.AlterField(
            model_name='hardwareassignment',
            name='from_date',
            field=models.DateField(default=inventory.models.default_from_date),
        ),
    ]
