# Generated by Django 5.1.2 on 2025-10-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_assignmenthistory_from_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwareassignment',
            options={'ordering': ['-created_at']},
        ),
    ]
