# Generated by Django 5.1.2 on 2025-10-17 05:12

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_hardwareassignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwareassignment',
            options={},
        ),
        migrations.AlterField(
            model_name='assignmenthistory',
            name='to_date',
            field=models.DateField(blank=True, default=inventory.models.default_to_date, null=True),
        ),
        migrations.AlterField(
            model_name='hardwareassignment',
            name='to_date',
            field=models.DateField(blank=True, default=inventory.models.default_to_date, null=True),
        ),
    ]
