# Generated by Django 5.2.9 on 2025-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_hardwareassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareassignment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
