# Generated by Django 5.2.9 on 2025-12-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_hardwareassignment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassignment',
            name='image',
            field=models.FileField(upload_to='hardware/images/'),
        ),
    ]
