# Generated by Django 5.1.2 on 2025-12-30 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_hardwareassignment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareassignment',
            name='configuration_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwareassignment',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardwareassignment',
            name='roboxa_asset_id',
            field=models.CharField(default='TEMP_ASSET', max_length=100),
        ),
        migrations.AddField(
            model_name='hardwareassignment',
            name='transfer_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hardwareassignment',
            name='transfer_from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hardwareassignment',
            name='transfer_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
