# Generated by Django 5.1.2 on 2025-12-30 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_hardwareassignment_configuration_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareassignment',
            name='transfer_to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
