# Generated by Django 5.1.2 on 2025-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_hardwareassignment_transfer_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassignment',
            name='transfer_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hardwareassignment',
            name='transfer_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
