# Generated by Django 5.1.2 on 2025-12-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_hardwareassignment_transfer_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareassignment',
            name='amc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwareassignment',
            name='amc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwareassignment',
            name='amc_vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hardwareassignment',
            name='warranty_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
