# Generated by Django 4.2.20 on 2025-06-03 12:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('project_description', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=30)),
                ('project_category', models.CharField(max_length=10)),
                ('project_status', models.CharField(max_length=10)),
                ('project_manager', models.CharField(max_length=80)),
                ('delivery_head', models.CharField(blank=True, max_length=80, null=True)),
                ('management', models.CharField(default='Sudhakara Varma Yarramraju', editable=False, max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('client_name', models.CharField(max_length=100)),
                ('project_region', models.CharField(max_length=60)),
                ('project_country', models.CharField(max_length=60)),
                ('delivery_model', models.CharField(max_length=20)),
                ('budgeted_hours', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('allocated_hours', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('allocated_budgeted_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999999.99'))])),
                ('allocated_budgeted_percentage', models.IntegerField(blank=True, null=True)),
                ('worked_hours', models.CharField(default='00:00', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('allocated_hours', models.PositiveIntegerField(default=0)),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.employee')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmo.project')),
                ('project_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.projectroles')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.projecttasks')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgeted_hours', models.BigIntegerField()),
                ('allocated_hours', models.PositiveIntegerField(default=0)),
                ('worked_hours', models.DurationField(default='00:00')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmo.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.projecttasks')),
            ],
        ),
    ]
