# Generated by Django 4.2.20 on 2025-06-03 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
