# Generated by Django 4.2.20 on 2025-06-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_projectroles_created_at_projectroles_updated_at_and_more'),
        ('pmo', '0002_projectteam_created_at_projectteam_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percent', models.FloatField(default=0)),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.employee')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmo.project')),
            ],
            options={
                'unique_together': {('employee_code', 'project_code')},
            },
        ),
    ]
