# Generated by Django 4.2.20 on 2025-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0002_project_allocated_budgeted_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allocated_budgeted_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
