# Generated by Django 4.2.20 on 2025-06-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0003_projectteamallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteamallocation',
            name='total_allocation_percent',
            field=models.FloatField(default=0),
        ),
    ]
