# Generated by Django 4.2.20 on 2025-06-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0004_projectteamallocation_total_allocation_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteamallocation',
            name='total_allocation_percent',
        ),
    ]
