# Generated by Django 4.2.20 on 2025-06-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_projectroles_created_at_projectroles_updated_at_and_more'),
        ('pmo', '0005_remove_projectteamallocation_total_allocation_percent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectteam',
            unique_together={('employee_code', 'project_code', 'task')},
        ),
    ]
