# Generated by Django 4.2.20 on 2025-06-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0006_alter_projectteam_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectteam',
            unique_together=set(),
        ),
    ]
