# Generated by Django 4.2.20 on 2025-06-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0007_alter_projectteam_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
