# Generated by Django 4.2.20 on 2025-06-28 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0008_project_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phaseallocation',
            name='worked_hours',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
