# Generated by Django 4.2.20 on 2025-06-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0009_alter_phaseallocation_worked_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phaseallocation',
            name='worked_hours',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
