# Generated by Django 5.1.2 on 2025-09-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0003_alter_project_allocated_budgeted_percentage'),
        ('pmo', '0010_alter_phaseallocation_worked_hours'),
    ]

    operations = [
    ]
