# Generated by Django 5.1.2 on 2025-09-02 10:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0011_merge_20250902_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contracting_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocated_budgeted_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999999.99'))]),
        ),
    ]
