# Generated by Django 5.1.2 on 2025-09-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0012_project_contracting_company_and_more'),
    ]

    operations = [
    ]
