# Generated by Django 5.1.2 on 2025-09-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0013_project_allocated_budgeted_hours_and_more'),
    ]

    operations = [
    ]
