# Generated by Django 5.1.2 on 2025-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0014_project_allocated_budgeted_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteamallocation',
            name='allocation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectteamallocation',
            name='allocation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
