# Generated by Django 5.1.2 on 2025-10-09 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0015_projectteamallocation_allocation_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamAllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percent', models.FloatField()),
                ('allocation_start_date', models.DateField()),
                ('allocation_end_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pmo.projectteamallocation')),
            ],
        ),
    ]
