# Generated by Django 5.1.2 on 2025-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0016_projectteamallocationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseallocation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaseallocation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
