# Generated by Django 5.1.2 on 2025-11-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0017_phaseallocation_end_date_phaseallocation_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteamallocationhistory',
            name='updated_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
