# Generated by Django 5.1.2 on 2025-11-26 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_employee_unique_non_empty_email'),
        ('pmo', '0018_projectteamallocationhistory_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTeamAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percent', models.FloatField(default=0)),
                ('allocation_start_date', models.DateField(blank=True, null=True)),
                ('allocation_end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmo.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.projecttasks')),
            ],
            options={
                'unique_together': {('employee', 'project', 'task')},
            },
        ),
        migrations.CreateModel(
            name='PhaseTeamAllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percent', models.FloatField()),
                ('allocation_start_date', models.DateField()),
                ('allocation_end_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pmo.phaseteamallocation')),
            ],
        ),
    ]
