# Generated by Django 5.1.2 on 2025-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0019_phaseteamallocation_phaseteamallocationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hr',
        ),
        migrations.AddField(
            model_name='project',
            name='sbu_head',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
