# Generated by Django 5.1.2 on 2025-12-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0020_remove_project_hr_project_sbu_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
