# Generated by Django 4.2.20 on 2025-06-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordrequest',
            name='confirm_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='forgotpasswordrequest',
            name='new_password',
            field=models.CharField(max_length=255),
        ),
    ]
