# Generated by Django 6.0 on 2025-12-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('employee_code', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('project_type', models.CharField(max_length=50)),
                ('project_code', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=100)),
                ('delivery_manager', models.CharField(max_length=100)),
                ('sbu_head', models.CharField(max_length=100)),
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_location', models.CharField(max_length=50)),
                ('travel_purpose', models.CharField(max_length=50)),
                ('others_specify', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_preferences', models.CharField(blank=True, max_length=50, null=True)),
                ('accommodation_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('PM Approved', 'PM Approved'), ('Finance Approved', 'Finance Approved'), ('Booking Completed', 'Booking Completed'), ('Rejected', 'Rejected')], default='Submitted', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_country', models.CharField(max_length=30)),
                ('departure_from', models.CharField(max_length=30)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_country', models.CharField(max_length=30)),
                ('arrival_to', models.CharField(max_length=30)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('mode', models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Road', 'Road')], max_length=10)),
                ('payment_by', models.CharField(blank=True, choices=[('Company', 'Company'), ('Self', 'Self')], max_length=10, null=True)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_details', to='travel_request.travelrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('id_document_type', models.CharField(max_length=30)),
                ('id_document_number', models.CharField(max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(max_length=12)),
                ('alt_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('alt_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('travel_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='travel_request.travelrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(blank=True, max_length=20, null=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_to', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='travel_request.travelrequest')),
            ],
        ),
    ]
