# Generated by Django 5.1.2 on 2025-12-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='country',
            field=models.CharField(default='India', max_length=30),
            preserve_default=False,
        ),
    ]
