# Generated by Django 5.1.2 on 2025-12-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_request', '0002_travelrequest_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetails',
            name='request_raised_by',
            field=models.CharField(default='Employee', max_length=100),
            preserve_default=False,
        ),
    ]
