# Generated by Django 5.1.2 on 2025-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_request', '0003_traveldetails_request_raised_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveldetails',
            name='request_raised_by',
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='request_raised_by',
            field=models.CharField(default='Employee', max_length=100),
            preserve_default=False,
        ),
    ]
