# Generated by Django 6.0 on 2025-12-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_request', '0004_remove_traveldetails_request_raised_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('PM Approved', 'PM Approved'), ('Delivery Approved', 'Delivery Approved'), ('SBU Approved', 'SBU Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=30),
        ),
    ]
