# Generated by Django 6.0 on 2025-12-26 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_request', '0005_alter_travelrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PM', 'Project Manager'), ('DELIVERY', 'Delivery Head'), ('SBU', 'SBU Head')], max_length=20)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('action_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('action_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='travel_request.travelrequest')),
            ],
        ),
    ]
