# Generated by Django 6.0 on 2025-12-26 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_request', '0006_approvalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='travel_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personaldetails', to='travel_request.travelrequest'),
        ),
    ]
