# Generated by Django 5.1.2 on 2025-12-16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
import software.models  # only for default_from_date


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=10)),
                ('asset_category', models.CharField(max_length=40)),
                ('asset_sub_category', models.CharField(max_length=40)),
                ('software_name', models.CharField(max_length=40)),
                ('minimum_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_key', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_tag', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('licensed_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=60)),
                ('user_name', models.CharField(max_length=40)),
                ('from_date', models.DateField(default=software.models.default_from_date)),
                ('to_date', models.DateField(blank=True, null=True)),  # nullable, read-only
                ('notes', models.CharField(blank=True, max_length=80, null=True)),
                ('location', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='software_images/')),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('byod', models.BooleanField(default=False)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=40, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),  # NEW FIELD
                ('invoice_copy', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('admin_user_name', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=255)),
                ('last_changed_by', models.CharField(default='system', max_length=50)),  # read-only
                ('last_changed_datetime', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'software_assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60)),
                ('user_name', models.CharField(max_length=40)),
                ('from_date', models.DateField(default=software.models.default_from_date)),
                ('to_date', models.DateField(blank=True, null=True)),  # read-only
                ('last_changed_by', models.CharField(default='system', max_length=50)),  # read-only
                ('last_changed_datetime', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='software.softwareassignment')),
            ],
            options={
                'db_table': 'software_assignment_history',
                'ordering': ['-from_date'],
            },
        ),
    ]
