# Generated by Django 5.1.2 on 2025-10-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareassignment',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
