# Generated by Django 5.1.2 on 2025-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_softwareassignment_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareassignment',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
