# Generated by Django 5.1.2 on 2025-12-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_softwareassignment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareassignment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='software_images/'),
        ),
    ]
