# Generated by Django 5.1.2 on 2025-12-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_alter_softwareassignment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareassignment',
            name='amc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareassignment',
            name='amc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareassignment',
            name='amc_vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='softwareassignment',
            name='roboxa_asset_id',
            field=models.CharField(default='TEMP_ASSET', max_length=100),
        ),
        migrations.AddField(
            model_name='softwareassignment',
            name='warranty_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
