# Generated by Django 5.1.2 on 2025-12-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_softwareassignment_amc_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareassignment',
            name='roboxa_asset_id',
            field=models.CharField(max_length=100),
        ),
    ]
