# Generated by Django 5.1.2 on 2026-01-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_alter_softwareassignment_roboxa_asset_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareassignment',
            name='currency',
        ),
    ]
